export const jobsData = [
    {
        id: 1,
        title: "Full Stack Developer",
        company: "Amazon",
        logoStyle: "bg-black text-white",
        experience: "1-3 yr Exp",
        workType: "Onsite",
        salary: "12 LPA",
        location: "Bangalore",
        jobType: "Full Time",
        salaryRange: 12,
        postedTime: "24h Ago",
        description: [
            "A user-friendly interface lets you browse stunning photos and videos",
            "Filter destinations based on interests and travel style, and create personalized",
        ],
    },
    {
        id: 2,
        title: "Node Js Developer",
        company: "Tesla",
        logoStyle: "bg-white border",
        experience: "1-3 yr Exp",
        workType: "Onsite",
        salary: "4",
        location: "Mumbai",
        jobType: "Part Time",
        salaryRange: 12,
        postedTime: "24h Ago",
        description: [
            "A user-friendly interface lets you browse stunning photos and videos",
            "Filter destinations based on interests and travel style, and create personalized",
        ],
    },
    {
        id: 3,
        title: "UX/UI Designer",
        company: "Swiggy",
        logoStyle: "bg-orange-500 text-white",
        experience: "1-3 yr Exp",
        workType: "Onsite",
        salary: "12 LPA",
        location: "Delhi",
        jobType: "Part Time",
        salaryRange: 12,
        postedTime: "24h Ago",
        description: [
            "A user-friendly interface lets you browse stunning photos and videos",
            "Filter destinations based on interests and travel style, and create personalized",
        ],
    },
    {
        id: 4,
        title: "Full Stack Developer",
        company: "Amazon",
        logoStyle: "bg-black text-white",
        experience: "1-3 yr Exp",
        workType: "Onsite",
        salary: "12 LPA",
        location: "Hyderabad",
        jobType: "Full Time",
        salaryRange: 12,
        postedTime: "24h Ago",
        description: [
            "A user-friendly interface lets you browse stunning photos and videos",
            "Filter destinations based on interests and travel style, and create personalized",
        ],
    },
    {
        id: 5,
        title: "Node Js Developer",
        company: "Tesla",
        logoStyle: "bg-white border",
        experience: "1-3 yr Exp",
        workType: "Onsite",
        salary: "12 LPA",
        location: "Pune",
        jobType: "Full Time",
        salaryRange: 12,
        postedTime: "24h Ago",
        description: [
            "A user-friendly interface lets you browse stunning photos and videos",
            "Filter destinations based on interests and travel style, and create personalized",
        ],
    },
    {
        id: 6,
        title: "UX/UI Designer",
        company: "Swiggy",
        logoStyle: "bg-orange-500 text-white",
        experience: "1-3 yr Exp",
        workType: "Onsite",
        salary: "12 LPA",
        location: "Chennai",
        jobType: "Full Time",
        salaryRange: 12,
        postedTime: "24h Ago",
        description: [
            "A user-friendly interface lets you browse stunning photos and videos",
            "Filter destinations based on interests and travel style, and create personalized",
        ],
    },
    {
        id: 7,
        title: "Full Stack Developer",
        company: "Amazon",
        logoStyle: "bg-black text-white",
        experience: "1-3 yr Exp",
        workType: "Onsite",
        salary: "12 LPA",
        location: "Kolkata",
        jobType: "Full Time",
        salaryRange: 12,
        postedTime: "24h Ago",
        description: [
            "A user-friendly interface lets you browse stunning photos and videos",
            "Filter destinations based on interests and travel style, and create personalized",
        ],
    },
    {
        id: 8,
        title: "Node Js Developer",
        company: "Tesla",
        logoStyle: "bg-white border",
        experience: "1-3 yr Exp",
        workType: "Onsite",
        salary: "12 LPA",
        location: "Gurgaon",
        jobType: "Full Time",
        salaryRange: 12,
        postedTime: "24h Ago",
        description: [
            "A user-friendly interface lets you browse stunning photos and videos",
            "Filter destinations based on interests and travel style, and create personalized",
        ],
    },
]